import "./globals.css";
import "./globalicons.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Geist, Geist_Mono } from "next/font/google";

import CVProvider from "@/contexts/CVProvider";
import TemplateProvider from "@/contexts/CVTemplateProvider";
import UserProfileProvider from "@/contexts/UserProfileProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CV Maker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProfileProvider>
          <TemplateProvider>
            <CVProvider>
              {children}
            </CVProvider>
          </TemplateProvider>
        </UserProfileProvider>
      </body>
    </html>
  );
}
