import "./globals.css";
import React from 'react';
import "./globalicons.css";
import App from "./App.js";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Geist, Geist_Mono } from "next/font/google";
import CVProvider from "@/contexts/CVProvider";
import AuthProvider from "@/contexts/AuthProvider";
import TemplateProvider from "@/contexts/CVTemplateProvider";
import UserProfileProvider from "@/contexts/UserProfileProvider";
import NotificationProvider from '@/contexts/NotificationProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CV Maker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NotificationProvider>
          <AuthProvider>
              <UserProfileProvider>
                  <TemplateProvider>
                      <CVProvider>
                        <App >
                          {children}
                        </App> 
                      </CVProvider>
                  </TemplateProvider>
              </UserProfileProvider>
          </AuthProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
